name: Build and check PKGBUILDs

on: [push]

jobs:
  python-tableone:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and check python-tableone
        uses: edlanglois/pkgbuild-action@v1
        with:
          pkgdir: "python-tableone"
  python-kodistubs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and check python-kodistubs
        uses: edlanglois/pkgbuild-action@v1
        with:
          pkgdir: "python-kodistubs"
  python-cursor:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and check python-cursor
        uses: edlanglois/pkgbuild-action@v1
        with:
          pkgdir: "python-cursor"
  kodi-addon-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and check kodi-addon-checker
        uses: edlanglois/pkgbuild-action@v1
        with:
          pkgdir: "kodi-addon-checker"
          aurDeps: 1
  sioyek:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build and check sioyek
        uses: edlanglois/pkgbuild-action@v1
        with:
          pkgdir: "sioyek"
