name: Check README.md

on: [push, pull_request]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: Set up Python 3.8
          uses: actions/setup-python@v4
          with:
              python-version: 3.8
        - name: Install dependencies
          run: |
              python -m pip install --upgrade pip
        - name: Test README.md
          run: |
              cd scripts/
              python generate_readme.py --check
